/**
 * Generated by scripts/build-client.mjs from src/client-core.js + src/client-app.js.
 * Do not edit by hand; regenerate with `npm run build:client`.
 */
window.__ModuleLoader__.load({
  id: "dsh-file-attach",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
/**
 * dsh-file-attach client core — pure, environment-agnostic helpers.
 *
 * This is a PLAIN SCRIPT (no import/export statements): scripts/build-client.mjs
 * inlines it verbatim into the web bundle factory, and tests load it through
 * `new Function`. The few functions that overlap with the host side
 * (lib/ingest.js) are intentionally mirrored here so the browser bundle stays
 * self-contained; keep the two copies in sync.
 */
var FileAttachCore = (function () {
  var IMAGE_MEDIA_TYPES = ['image/png', 'image/jpeg', 'image/webp', 'image/gif']
  var IMAGE_EXTENSIONS = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif' }

  function extensionOfName(name) {
    var base = String(name == null ? '' : name).replace(/\\/g, '/').split('/').pop() || ''
    var dot = base.lastIndexOf('.')
    return dot <= 0 ? '' : base.slice(dot + 1).toLowerCase()
  }

  /** 'image' for raster MIMEs, else 'file'. */
  function classifyFile(mime) {
    return IMAGE_MEDIA_TYPES.indexOf(mime) !== -1 ? 'image' : 'file'
  }

  /** True when declared MIME or filename is a PNG/JPEG/WebP/GIF raster. */
  function isRasterImage(file) {
    if (file == null) return false
    var mime = file.type || file.mime
    if (IMAGE_MEDIA_TYPES.indexOf(mime) !== -1) return true
    return Object.prototype.hasOwnProperty.call(IMAGE_EXTENSIONS, extensionOfName(file.name))
  }

  /** Canonical raster MIME from declared type or filename extension. */
  function rasterMediaType(file) {
    if (file == null) return undefined
    var mime = file.type || file.mime
    if (IMAGE_MEDIA_TYPES.indexOf(mime) !== -1) return mime
    var mapped = IMAGE_EXTENSIONS[extensionOfName(file.name)]
    return mapped === undefined ? undefined : mapped
  }

  /** Split a File-like list into rasters vs everything else. */
  function partitionIntake(files) {
    var images = []
    var others = []
    var list = files == null ? [] : files
    for (var i = 0; i < list.length; i += 1) {
      if (isRasterImage(list[i])) images.push(list[i])
      else others.push(list[i])
    }
    return { images: images, others: others }
  }

  /**
   * True only when the catalog entry explicitly lists `image` input.
   * Missing inputModalities is unknown, not visual.
   */
  function modelSupportsVisual(info) {
    return info != null && Array.isArray(info.inputModalities) && info.inputModalities.indexOf('image') !== -1
  }

  /** Compact human-readable byte count (e.g. "2.4 MB"). */
  function humanSize(bytes) {
    if (!Number.isFinite(bytes) || bytes < 0) return '0 B'
    if (bytes < 1024) return bytes + ' B'
    var units = ['KB', 'MB', 'GB', 'TB']
    var value = bytes
    var unit = -1
    do {
      value /= 1024
      unit += 1
    } while (value >= 1024 && unit < units.length - 1)
    return (value >= 100 ? Math.round(value) : value.toFixed(1)) + ' ' + units[unit]
  }

  /** Marker wrapping extract text in the model form. Hidden in the conversation UI. */
  var EXTRACT_FENCE_START = '----- extracted content -----'
  var EXTRACT_FENCE_END = '----- end -----'
  var EXTRACT_FENCE_RE = /\r?\n----- extracted content -----\r?\n[\s\S]*?\r?\n----- end -----/g

  /** Header line shared by the model form and the user-visible display form. */
  function attachHeader(meta) {
    var idBit = meta && meta.id ? ' id=' + meta.id : ''
    if (!meta || meta.name === undefined) {
      return '[attached file' + idBit + ' — extraction unavailable after reload; use attach_* tools with id ' + (meta && meta.id) + ']'
    }
    var sizeBit = meta.size !== undefined ? ' (' + humanSize(meta.size) + ')' : ''
    return '[attached file "' + meta.name + '"' + sizeBit + idBit + ']'
  }

  /**
   * User-visible form of one attachment: the header only, never the extract
   * fence. Vault paths are never included.
   */
  function displayForm(meta) {
    return attachHeader(meta)
  }

  /**
   * The model-visible form of one attachment: extracted text when present,
   * otherwise a degraded id hint. Vault paths are never included.
   */
  function modelForm(meta) {
    var header = attachHeader(meta)
    var extractText = meta && meta.extract && typeof meta.extract.text === 'string' ? meta.extract.text : undefined
    if (extractText !== undefined && meta && meta.name !== undefined) {
      return header + '\n' + EXTRACT_FENCE_START + '\n' + extractText + '\n' + EXTRACT_FENCE_END
    }
    return header
  }

  /** Drop extract fences so conversation UI can show the header without the prompt body. */
  function stripExtractForDisplay(text) {
    EXTRACT_FENCE_RE.lastIndex = 0
    return String(text).replace(EXTRACT_FENCE_RE, '')
  }

  /**
   * Rewrite text nodes under `root` so extract fences never paint.
   * Skips the composer (chips already hide the model form).
   */
  function hideExtractInTree(root) {
    if (root === undefined || root === null) return false
    if (inComposer(root)) return false
    if (root.nodeType === 3) {
      var value = root.nodeValue
      if (typeof value !== 'string' || value.indexOf(EXTRACT_FENCE_START) === -1) return false
      var next = stripExtractForDisplay(value)
      if (next === value) return false
      root.nodeValue = next
      return true
    }
    var changed = false
    if (typeof root.textContent === 'string' && root.textContent.indexOf(EXTRACT_FENCE_START) !== -1) {
      var child = root.firstChild
      if (child !== null && child.nextSibling === null && child.nodeType === 3) {
        return hideExtractInTree(child)
      }
      var onlyText = true
      var cursor = root.firstChild
      while (cursor !== null) {
        if (cursor.nodeType === 1) { onlyText = false; break }
        cursor = cursor.nextSibling
      }
      if (onlyText && root.firstChild !== null) {
        var stripped = stripExtractForDisplay(root.textContent)
        if (stripped !== root.textContent) {
          root.textContent = stripped
          return true
        }
      }
    }
    var walk = root.firstChild
    while (walk !== null) {
      var sibling = walk.nextSibling
      if (hideExtractInTree(walk)) changed = true
      walk = sibling
    }
    return changed
  }

  function inComposer(node) {
    var el = node
    if (el !== undefined && el !== null && el.nodeType === 3) el = el.parentElement || el.parentNode
    if (el === undefined || el === null || typeof el.closest !== 'function') return false
    return el.closest('[data-composer-card], textarea, [data-input-backdrop], [data-input-mirror]') !== null
  }

  /**
   * Geometry that tracks the composer card: DSH publishes
   * `--dsh-composer-card-max-width` on the conversation root (content width +
   * 32px). The file-list dock sits in the full-width `conversation.input.dock`
   * slot above that card, so it must opt into the same cap and centering.
   */
  function composerAlignedBox() {
    return {
      boxSizing: 'border-box',
      width: '100%',
      maxWidth: 'var(--dsh-composer-card-max-width, 780px)',
      alignSelf: 'center',
      marginLeft: 'auto',
      marginRight: 'auto',
    }
  }

  /**
   * End-of-draft insertion span for a reference chip.
   * @returns a TokenSpan placing the placeholder at the end of the draft.
   */
  function endOfDraftSpan(draft, draftRev) {
    var at = typeof draft === 'string' ? draft.length : 0
    return { start: at, end: at, draftRev: draftRev }
  }

  /** Parse a trimmed draft line as a plain-text `/attach <id>` reference; null when not one. */
  function parseAttachLine(line) {
    var m = /^\/attach\s+(\S+)\s*$/.exec(String(line).trim())
    return m === null ? null : m[1]
  }

  /** Chunk plan for one file: zero-based [start, end) byte ranges of at most chunkBytes. */
  function chunkPlan(size, chunkBytes) {
    var plan = []
    if (size <= 0) return plan
    for (var start = 0; start < size; start += chunkBytes) {
      plan.push({ start: start, end: Math.min(size, start + chunkBytes) })
    }
    return plan
  }

  return {
    classifyFile: classifyFile,
    isRasterImage: isRasterImage,
    rasterMediaType: rasterMediaType,
    partitionIntake: partitionIntake,
    modelSupportsVisual: modelSupportsVisual,
    humanSize: humanSize,
    displayForm: displayForm,
    modelForm: modelForm,
    stripExtractForDisplay: stripExtractForDisplay,
    hideExtractInTree: hideExtractInTree,
    composerAlignedBox: composerAlignedBox,
    EXTRACT_FENCE_START: EXTRACT_FENCE_START,
    EXTRACT_FENCE_END: EXTRACT_FENCE_END,
    endOfDraftSpan: endOfDraftSpan,
    parseAttachLine: parseAttachLine,
    chunkPlan: chunkPlan,
  }
})()

/**
 * dsh-file-attach CLIENT plugin body.
 *
 * Plain script (no imports/exports): scripts/build-client.mjs inlines this
 * file and src/client-core.js into the web bundle factory, where
 * `buildFileAttachPlugin(env)` returns the cordis plugin { name, inject, apply }.
 * `env.React` and `env.Core` (FileAttachCore) are provided by the build.
 *
 * What it does:
 *  1. Capture-phase drop/paste interception. Raster images go to DSH's built-in
 *     composer vision path when the current model declares `image` input;
 *     otherwise they (and every non-image file) use this plugin's extract path.
 *  2. Chunked binary upload to the host half (POST /api/dsh-file-attach/upload).
 *  3. On success, inserts a reference chip into the composer draft through the
 *     scoped `slash/input-insert-reference` event. The host extract is spliced
 *     into the model form at serialize time. The conversation UI strips the
 *     extract fence and shows only the `[attached file …]` header.
 *  4. A `conversation.input.dock` strip aligned to the composer card width:
 *     upload progress + the session's attached files + an Add picker.
 *  5. A `/attach` input-trigger source whose `matchEnter` recovers a plain-text
 *     `/attach <id>` line after a page reload.
 */
function buildFileAttachPlugin(env) {
  var React = env.React
  var Core = env.Core

  var NS = 'fileAttach'
  var SOURCE_NAME = 'attach'
  var ROUTE_UPLOAD = '/api/dsh-file-attach/upload'
  var ROUTE_ABORT = '/api/dsh-file-attach/abort'
  var ROUTE_CONFIG = '/api/dsh-file-attach/config'
  var ROUTE_EXTRACT = '/api/dsh-file-attach/extract'
  var ROUTE_VISION = '/api/dsh-file-attach/vision'
  var DEFAULT_LIMITS = {
    maxFileBytes: 50 * 1024 * 1024,
    maxFilesPerMessage: 20,
    maxConcurrentUploads: 20,
    chunkBytes: 1024 * 1024,
  }

  var dictionaries = {
    zh: {
      attach: '上传文件',
      menuAttach: '上传文件…',
      addFiles: '添加',
      extracting: '正在提取 {name}',
      failed: '上传 {name} 失败：{message}',
      tooLarge: '{name} 超过大小限制 {size}',
      empty: '{name} 是空文件',
      noSession: '没有可附加文件的会话',
      busy: '正在处理中，请稍后再附加文件',
      insertFailed: '无法插入 {name} 的引用',
    },
    en: {
      attach: 'Attach files',
      menuAttach: 'Attach files…',
      addFiles: 'Add',
      extracting: 'Extracting {name}',
      failed: 'Upload of {name} failed: {message}',
      tooLarge: '{name} exceeds the {size} limit',
      empty: '{name} is empty',
      noSession: 'No active session to attach files to',
      busy: 'The conversation is busy; attach files in a moment',
      insertFailed: 'Could not insert the reference for {name}',
    },
  }

  return {
    name: 'file-attach',
    inject: ['slots', 'locale', 'inputTriggers', 'sessions', 'conversation', 'commandUi'],

    apply: function apply(ctx) {
      var t = ctx.locale.bind(NS)
      ctx.effect(function () {
        return ctx.locale.register(NS, dictionaries)
      }, 'file-attach: dictionaries')

      /** ref (upload id) -> { id, name, size, extract } for codec serialization. */
      var metaByRef = new Map()
      /** Live upload AbortControllers, aborted on plugin disposal. */
      var activeUploads = new Set()
      /** Client-mirrored limits (refreshed from the host config route, best effort). */
      var limitsRef = { current: DEFAULT_LIMITS }
      /** Last vision lookup: `{ sessionId, visual }` so paste can stay synchronous. */
      var visualCache = { sessionId: null, visual: false }

      /** Session-scoped dock rows: uploading / extracting / ready. */
      var dockItems = []
      var dockListeners = new Set()
      var dockSeq = 0

      function dockPing() {
        dockListeners.forEach(function (fn) { fn() })
      }

      function dockUpsert(partial) {
        var found = -1
        for (var i = 0; i < dockItems.length; i += 1) {
          if (dockItems[i].key === partial.key) { found = i; break }
        }
        if (found === -1) dockItems.push(partial)
        else dockItems[found] = Object.assign({}, dockItems[found], partial)
        dockPing()
      }

      function dockRemove(key) {
        dockItems = dockItems.filter(function (item) { return item.key !== key })
        dockPing()
      }

      function dockForSession(sessionId) {
        return dockItems.filter(function (item) { return item.sessionId === sessionId })
      }

      // ── host config mirror ──────────────────────────────────────────────
      fetch(ROUTE_CONFIG)
        .then(function (resp) { return resp.ok ? resp.json() : null })
        .then(function (body) {
          if (body === null || typeof body !== 'object') return
          limitsRef.current = {
            maxFileBytes: numberOr(body.maxFileBytes, limitsRef.current.maxFileBytes),
            maxFilesPerMessage: numberOr(body.maxFilesPerMessage, limitsRef.current.maxFilesPerMessage),
            maxConcurrentUploads: numberOr(body.maxConcurrentUploads, limitsRef.current.maxConcurrentUploads),
            chunkBytes: limitsRef.current.chunkBytes,
          }
        })
        .catch(function () { /* defaults stand */ })

      function numberOr(value, fallback) {
        return typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : fallback
      }

      // ── session addressing ──────────────────────────────────────────────
      function currentSessionId() {
        var list = ctx.sessions.list.getSnapshot()
        return list === undefined || list === null ? undefined : list.current
      }

      function sessionFace(sessionId) {
        if (sessionId === undefined || sessionId === null) return undefined
        var actx = ctx.sessions.scope(sessionId)
        if (actx === undefined) return undefined
        var input = ctx.conversation.input.for(actx)
        return { actx: actx, input: input }
      }

      function toast(sessionId, level, text) {
        var face = sessionFace(sessionId)
        if (face !== undefined) face.input.notify(level, text)
      }

      // ── current-model visual capability ─────────────────────────────────
      function composerSelection(sessionId) {
        var dirs = typeof ctx.get === 'function' ? ctx.get('modelDirectories') : ctx.modelDirectories
        if (dirs == null || typeof dirs.directoryFor !== 'function') return null
        try {
          var store = dirs.directoryFor(sessionId).store
          var snap = store && typeof store.getSnapshot === 'function' ? store.getSnapshot() : null
          var current = snap && snap.current
          if (current == null || typeof current.provider !== 'string' || typeof current.model !== 'string') return null
          return current
        } catch {
          return null
        }
      }

      function fetchVisual(sessionId) {
        if (sessionId === undefined || sessionId === null) {
          visualCache.sessionId = null
          visualCache.visual = false
          return Promise.resolve(false)
        }
        var headers = { 'x-session-id': sessionId }
        var selection = composerSelection(sessionId)
        if (selection !== null) {
          headers['x-provider'] = selection.provider
          headers['x-model'] = selection.model
        }
        return fetch(ROUTE_VISION, {
          method: 'GET',
          headers: headers,
        }).then(function (resp) {
          return resp.ok ? resp.json() : { visual: false }
        }).then(function (body) {
          var visual = body !== null && typeof body === 'object' && body.visual === true
          visualCache.sessionId = sessionId
          visualCache.visual = visual
          return visual
        }).catch(function () {
          visualCache.sessionId = sessionId
          visualCache.visual = false
          return false
        })
      }

      /**
       * Hand rasters to DSH's composer image rail (createDraftImages + addImages).
       * @returns true when the built-in path accepted the batch.
       */
      function addViaDefaultPipeline(sessionId, files) {
        if (files.length === 0) return true
        var conversation = ctx.conversation
        var face = sessionFace(sessionId)
        if (
          conversation == null
          || typeof conversation.createDraftImages !== 'function'
          || face === undefined
          || typeof face.input.addImages !== 'function'
        ) {
          return false
        }
        var prepared = []
        for (var i = 0; i < files.length; i += 1) {
          prepared.push(withRasterType(files[i]))
        }
        try {
          var images = conversation.createDraftImages(prepared)
          if (!face.input.addImages(images.map(function (img) { return img.id }))) {
            if (typeof conversation.releaseDraftImages === 'function') {
              conversation.releaseDraftImages(images)
            }
            return false
          }
          return true
        } catch {
          return false
        }
      }

      function withRasterType(file) {
        var mime = Core.rasterMediaType(file)
        if (mime === undefined || mime === file.type || typeof File !== 'function') return file
        try {
          return new File([file], file.name, { type: mime, lastModified: file.lastModified })
        } catch {
          return file
        }
      }

      /** Images → native vision when the model is visual; otherwise plugin extract. */
      function routeFiles(sessionId, files) {
        if (files.length === 0) return
        void fetchVisual(sessionId).then(function (visual) {
          var parts = Core.partitionIntake(files)
          if (visual && parts.images.length > 0) {
            if (!addViaDefaultPipeline(sessionId, parts.images)) {
              for (var i = 0; i < parts.images.length; i += 1) intake(sessionId, parts.images[i])
            }
          } else {
            for (var j = 0; j < parts.images.length; j += 1) intake(sessionId, parts.images[j])
          }
          for (var k = 0; k < parts.others.length; k += 1) intake(sessionId, parts.others[k])
        })
      }

      function filesFromClipboard(clipboard) {
        var out = []
        if (clipboard == null) return out
        var items = clipboard.items
        if (items != null) {
          for (var i = 0; i < items.length; i += 1) {
            if (items[i].kind !== 'file') continue
            var asFile = typeof items[i].getAsFile === 'function' ? items[i].getAsFile() : null
            if (asFile != null) out.push(asFile)
          }
          if (out.length > 0) return out
        }
        var list = clipboard.files
        if (list == null) return out
        for (var j = 0; j < list.length; j += 1) out.push(list[j])
        return out
      }

      // ── upload ──────────────────────────────────────────────────────────
      function uploadFile(sessionId, file, limits, signal, onProgress) {
        var plan = Core.chunkPlan(file.size, limits.chunkBytes)
        var uploadId = null
        var index = 0
        var step = function () {
          if (signal !== undefined && signal.aborted) {
            return Promise.reject(abortError())
          }
          var range = plan[index]
          var last = index === plan.length - 1
          if (last && typeof onProgress === 'function') {
            onProgress({
              id: uploadId,
              received: Math.max(range.start, Math.floor(file.size * 0.95)),
              total: file.size,
              phase: 'extracting',
            })
          }
          var headers = {
            'content-type': 'application/octet-stream',
            'x-session-id': sessionId,
            'x-file-name': encodeURIComponent(file.name),
            'x-file-type': file.type || 'application/octet-stream',
            'x-file-size': String(file.size),
            'x-chunk-index': String(index),
            'x-chunk-count': String(plan.length),
          }
          if (uploadId !== null) headers['x-upload-id'] = uploadId
          return file
            .slice(range.start, range.end)
            .arrayBuffer()
            .then(function (buffer) {
              return fetch(ROUTE_UPLOAD, {
                method: 'POST',
                headers: headers,
                body: buffer,
                signal: signal,
              })
            })
            .then(function (resp) {
              return resp.json().catch(function () { return {} }).then(function (body) {
                if (!resp.ok) {
                  var err = new Error((body.error && body.error.message) || ('upload failed with status ' + resp.status))
                  err.code = body.error && body.error.code
                  throw err
                }
                if (uploadId === null) uploadId = body.id
                if (last) return body
                if (typeof onProgress === 'function') {
                  onProgress({
                    id: uploadId,
                    received: typeof body.received === 'number' ? body.received : range.end,
                    total: typeof body.total === 'number' ? body.total : file.size,
                    phase: 'uploading',
                  })
                }
                index += 1
                return step()
              })
            })
        }
        var run = step()
        run.catch(function () {
          if (uploadId !== null) abortUpload(uploadId)
        })
        return run
      }

      function abortError() {
        var err = new Error('aborted')
        err.name = 'AbortError'
        return err
      }

      function abortUpload(uploadId) {
        void fetch(ROUTE_ABORT, {
          method: 'POST',
          headers: { 'x-upload-id': uploadId },
          keepalive: true,
        }).catch(function () { /* best effort */ })
      }

      // ── intake ──────────────────────────────────────────────────────────
      function intake(sessionId, file) {
        var limits = limitsRef.current
        if (file.size === 0) return toast(sessionId, 'error', t('empty', { name: file.name }))
        if (file.size > limits.maxFileBytes) {
          return toast(sessionId, 'error', t('tooLarge', { name: file.name, size: Core.humanSize(limits.maxFileBytes) }))
        }
        var face = sessionFace(sessionId)
        if (face !== undefined) {
          var phase = face.input.state.getSnapshot().phase
          if (phase !== 'plain' && phase !== 'claimed') {
            return toast(sessionId, 'error', t('busy'))
          }
        }
        var controller = new AbortController()
        activeUploads.add(controller)
        dockSeq += 1
        var key = 'up-' + dockSeq
        dockUpsert({
          key: key,
          sessionId: sessionId,
          name: file.name,
          size: file.size,
          phase: 'uploading',
          received: 0,
          total: file.size,
        })
        uploadFile(sessionId, file, limits, controller.signal, function (progress) {
          dockUpsert({
            key: key,
            sessionId: sessionId,
            name: file.name,
            size: file.size,
            id: progress.id,
            phase: progress.phase,
            received: progress.received,
            total: progress.total,
          })
        })
          .then(function (meta) {
            activeUploads.delete(controller)
            dockUpsert({
              key: key,
              sessionId: sessionId,
              id: meta.id,
              name: meta.name,
              size: meta.size,
              phase: 'ready',
              received: meta.size,
              total: meta.size,
            })
            insertChip(sessionId, meta)
          })
          .catch(function (error) {
            activeUploads.delete(controller)
            dockRemove(key)
            if (error !== null && error !== undefined && error.name === 'AbortError') return
            toast(sessionId, 'error', t('failed', {
              name: file.name,
              message: error !== null && error !== undefined && error.message !== undefined ? error.message : String(error),
            }))
          })
      }

      // ── chip insertion ───────────────────────────────────────────────────
      function insertChip(sessionId, meta) {
        var face = sessionFace(sessionId)
        if (face === undefined) return false
        metaByRef.set(meta.id, meta)
        var reference = {
          source: SOURCE_NAME,
          ref: meta.id,
          label: meta.name,
          clipboardText: '/attach ' + meta.id,
        }
        for (var attempt = 0; attempt < 2; attempt += 1) {
          var state = face.input.state.getSnapshot()
          var span = Core.endOfDraftSpan(state.draft, state.draftRev)
          var applied = face.actx.bail(face.actx, 'slash/input-insert-reference', { reference: reference, span: span }) === true
          if (applied) return true
        }
        toast(sessionId, 'error', t('insertFailed', { name: meta.name }))
        return false
      }

      // ── model form ───────────────────────────────────────────────────────
      function modelFormOf(ref) {
        var meta = metaByRef.get(ref)
        return Core.modelForm(meta === undefined ? { id: ref } : meta)
      }

      function fetchExtract(sessionId, ref) {
        return fetch(ROUTE_EXTRACT, {
          method: 'GET',
          headers: { 'x-session-id': sessionId, 'x-upload-id': ref },
        }).then(function (resp) {
          return resp.ok ? resp.json() : null
        }).catch(function () { return null })
      }

      function serializeRef(ref) {
        var meta = metaByRef.get(ref)
        if (meta !== undefined && meta.extract !== undefined) {
          return Promise.resolve(modelFormOf(ref))
        }
        var sessionId = currentSessionId()
        if (sessionId === undefined || sessionId === null) {
          return Promise.resolve(modelFormOf(ref))
        }
        return fetchExtract(sessionId, ref).then(function (extract) {
          if (extract !== null && typeof extract === 'object') {
            var merged = Object.assign({ id: ref }, meta || {}, { extract: extract })
            if (meta !== undefined) {
              merged.name = meta.name
              merged.size = meta.size
            }
            metaByRef.set(ref, merged)
          }
          return modelFormOf(ref)
        })
      }

      // ── input-trigger source ─────────────────────────────────────────────
      // Codec + `/attach <id>` enter recovery. The slash *menu* row is a
      // commandUi contribution so it lands in the same catalog as compact/export.
      var source = {
        trigger: '/',
        name: SOURCE_NAME,
        order: 90,
        showGroupTitle: false,
        candidates: function () {
          return Promise.resolve([])
        },
        onPick: function () {
          return undefined
        },
        lexicon: function () {
          return Array.from(metaByRef.keys())
        },
        matchEnter: function (session, line) {
          var ref = Core.parseAttachLine(line)
          if (ref === null) return undefined
          return {
            claim: {
              token: '/attach ',
              submit: function (args) {
                return sendRecovered(session.sessionId, modelFormOf(args.trim()))
              },
            },
          }
        },
        codec: {
          clipboardText: function (ref) { return '/attach ' + ref },
          serialize: function (ref, signal) {
            return serializeRef(ref)
          },
        },
      }
      ctx.effect(function () {
        return ctx.inputTriggers.registerSource(source)
      }, 'file-attach: input-trigger source')

      function closePopup(sessionId) {
        try {
          var input = ctx.conversation && ctx.conversation.input
          if (input !== undefined && typeof input.shell === 'function') {
            input.shell(sessionId).dismissPopup()
          }
        } catch {
          /* popup already gone */
        }
      }

      ctx.effect(function () {
        if (ctx.commandUi === undefined || typeof ctx.commandUi.register !== 'function') return
        return ctx.commandUi.register({
          name: 'attach',
          description: t('menuAttach'),
          available: function (session) {
            return typeof ctx.sessions.subagentAddress !== 'function'
              || ctx.sessions.subagentAddress(session.sessionId) === undefined
          },
          ui: {
            kind: 'popupSelect',
            options: function (session) {
              closePopup(session.sessionId)
              pickFiles(session.sessionId)
              return Promise.resolve([{ id: 'attach', label: t('menuAttach') }])
            },
            onSelect: function () {},
          },
        })
      }, 'file-attach: command contribution')

      function sendRecovered(sessionId, text) {
        var face = sessionFace(sessionId)
        if (face === undefined) return Promise.resolve({ kind: 'error', text: 'no active session' })
        var session = ctx.sessions.sessionOf(face.actx)
        if (session === undefined) return Promise.resolve({ kind: 'error', text: 'no session object' })
        return session.prompt([{ type: 'text', text: text }], 'queue').then(function (result) {
          if (!result.ok) return { kind: 'error', text: result.error.code + ': ' + result.error.message }
          return { kind: 'success' }
        }, function (error) {
          return { kind: 'error', text: error instanceof Error ? error.message : String(error) }
        })
      }

      // ── file picker (dock Add + '/' menu entry) ─────────────────────────
      function pickFiles(sessionId) {
        var input = document.createElement('input')
        input.type = 'file'
        input.multiple = true
        input.onchange = function () {
          var files = input.files
          if (files !== null) {
            var batch = []
            for (var i = 0; i < files.length; i += 1) batch.push(files[i])
            routeFiles(sessionId, batch)
          }
          input.remove()
        }
        input.click()
      }

      // ── drop interception (capture phase: runs before the built-in listener) ──
      function hasFileDrag(event) {
        var dt = event.dataTransfer
        if (dt === null || dt === undefined) return false
        var types = dt.types
        if (types === undefined || types === null) return false
        for (var i = 0; i < types.length; i += 1) {
          if (types[i] === 'Files') return true
        }
        return false
      }

      var onDragOverCapture = function (event) {
        if (!hasFileDrag(event)) return
        event.preventDefault()
        if (event.dataTransfer !== null) event.dataTransfer.dropEffect = 'copy'
      }

      var onDropCapture = function (event) {
        var dt = event.dataTransfer
        if (dt === null || dt === undefined || dt.files === undefined || dt.files === null || dt.files.length === 0) return
        var files = []
        for (var i = 0; i < dt.files.length; i += 1) files.push(dt.files[i])
        event.preventDefault()
        event.stopPropagation()
        window.dispatchEvent(new Event('dragend'))
        var sessionId = currentSessionId()
        if (sessionId === undefined || sessionId === null) {
          console.warn('[file-attach] drop ignored: no active session')
          return
        }
        routeFiles(sessionId, files)
      }

      var onPasteCapture = function (event) {
        var clipboard = event.clipboardData
        var files = filesFromClipboard(clipboard)
        if (files.length === 0) return
        var parts = Core.partitionIntake(files)
        if (parts.images.length === 0) return
        event.preventDefault()
        event.stopPropagation()
        var sessionId = currentSessionId()
        if (sessionId === undefined || sessionId === null) {
          console.warn('[file-attach] paste ignored: no active session')
          return
        }
        var text = clipboard !== null && clipboard !== undefined && typeof clipboard.getData === 'function'
          ? clipboard.getData('text/plain')
          : ''
        void fetchVisual(sessionId).then(function (visual) {
          if (visual && parts.images.length > 0) {
            if (!addViaDefaultPipeline(sessionId, parts.images)) {
              for (var i = 0; i < parts.images.length; i += 1) intake(sessionId, parts.images[i])
            }
          } else {
            for (var j = 0; j < parts.images.length; j += 1) intake(sessionId, parts.images[j])
          }
          for (var k = 0; k < parts.others.length; k += 1) intake(sessionId, parts.others[k])
          if (typeof text === 'string' && text !== '') {
            var face = sessionFace(sessionId)
            if (face !== undefined && typeof face.input.setDraft === 'function') {
              var draft = face.input.state.getSnapshot().draft || ''
              face.input.setDraft(draft + text)
            }
          }
        })
      }

      document.addEventListener('dragover', onDragOverCapture, true)
      document.addEventListener('drop', onDropCapture, true)
      document.addEventListener('paste', onPasteCapture, true)

      void fetchVisual(currentSessionId())

      // ── dock: progress + file list (conversation.input.dock) ────────────
      // The dock slot is a full-width row above the composer card. Opt into
      // DSH's shared composer width axis so the file list matches the card.
      var aligned = Core.composerAlignedBox()
      var dockStyle = {
        root: Object.assign({
          display: 'flex',
          flexDirection: 'column',
          gap: '6px',
          padding: '4px 0',
          color: 'var(--dsw-fg, inherit)',
          fontSize: '12px',
        }, aligned),
        row: {
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          minWidth: 0,
        },
        chips: {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '6px',
          flex: '1 1 auto',
          minWidth: 0,
        },
        chip: {
          display: 'inline-flex',
          alignItems: 'baseline',
          gap: '6px',
          maxWidth: '100%',
          padding: '2px 8px',
          border: '1px solid var(--dsw-border, currentColor)',
          borderRadius: '999px',
          lineHeight: '1.4',
          overflow: 'hidden',
        },
        chipName: {
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        chipSize: {
          opacity: 0.65,
          flex: '0 0 auto',
        },
        barWrap: {
          flex: '1 1 auto',
          minWidth: 0,
        },
        bar: {
          display: 'block',
          width: '100%',
          height: '4px',
          accentColor: 'var(--dsw-accent, currentColor)',
        },
        status: {
          flex: '0 0 auto',
          opacity: 0.75,
          whiteSpace: 'nowrap',
        },
        add: {
          flex: '0 0 auto',
          marginLeft: 'auto',
          padding: '2px 8px',
          border: '1px solid var(--dsw-border, currentColor)',
          borderRadius: '6px',
          background: 'transparent',
          color: 'inherit',
          cursor: 'pointer',
          fontSize: '12px',
        },
      }

      function AttachDock(props) {
        var sessionId = props.sessionId
        var bump = React.useState(0)
        var setRev = bump[1]
        React.useEffect(function () {
          function ping() { setRev(function (n) { return n + 1 }) }
          dockListeners.add(ping)
          return function () { dockListeners.delete(ping) }
        }, [])
        var items = dockForSession(sessionId)
        if (items.length === 0) return null
        var inflight = items.filter(function (item) {
          return item.phase === 'uploading' || item.phase === 'extracting'
        })
        var ready = items.filter(function (item) { return item.phase === 'ready' })
        var children = []
        if (inflight.length > 0) {
          var received = 0
          var total = 0
          for (var i = 0; i < inflight.length; i += 1) {
            received += inflight[i].received || 0
            total += inflight[i].total || 0
          }
          var extracting = inflight.some(function (item) { return item.phase === 'extracting' })
          var label = extracting
            ? t('extracting', { name: inflight[0].name })
            : Core.humanSize(received) + ' / ' + Core.humanSize(total)
          children.push(React.createElement('div', { key: 'progress', style: dockStyle.row },
            React.createElement('div', { style: dockStyle.barWrap },
              React.createElement('progress', {
                style: dockStyle.bar,
                value: total > 0 ? received : 0,
                max: total > 0 ? total : 1,
              }),
            ),
            React.createElement('span', { style: dockStyle.status }, label),
          ))
        }
        var chipNodes = ready.map(function (item) {
          return React.createElement('span', { key: item.id || item.key, style: dockStyle.chip },
            React.createElement('span', { style: dockStyle.chipName }, item.name),
            item.size !== undefined
              ? React.createElement('span', { style: dockStyle.chipSize }, Core.humanSize(item.size))
              : null,
          )
        })
        children.push(React.createElement('div', { key: 'files', style: dockStyle.row },
          React.createElement('div', { style: dockStyle.chips }, chipNodes),
          React.createElement('button', {
            type: 'button',
            style: dockStyle.add,
            'aria-label': t('attach'),
            title: t('attach'),
            onClick: function () { props.attach(sessionId) },
          }, t('addFiles')),
        ))
        return React.createElement('div', { style: dockStyle.root }, children)
      }

      ctx.slots.inject('conversation.input.dock', function () {
        return ctx.slots.register({
          name: 'conversation.input.dock',
          id: 'file-attach',
          locale: NS,
          inject: function () {
            return {
              attach: function (sessionId) { pickFiles(sessionId) },
            }
          },
        }, AttachDock)
      })

      // ── hide extract fences in conversation UI (model form stays intact) ──
      function hideExtractFromUi(target) {
        Core.hideExtractInTree(target === undefined || target === null ? document.body : target)
      }

      var extractObserver = null
      var extractPoll = null
      if (typeof MutationObserver === 'function' && document.body !== undefined && document.body !== null) {
        extractObserver = new MutationObserver(function (records) {
          for (var r = 0; r < records.length; r += 1) {
            var record = records[r]
            if (record.type === 'characterData') {
              hideExtractFromUi(record.target)
              continue
            }
            var added = record.addedNodes
            if (added === undefined || added === null) continue
            for (var n = 0; n < added.length; n += 1) hideExtractFromUi(added[n])
          }
        })
        extractObserver.observe(document.documentElement || document.body, {
          childList: true,
          subtree: true,
          characterData: true,
        })
        hideExtractFromUi(document.body)
        extractPoll = setInterval(function () { hideExtractFromUi(document.body) }, 1000)
        if (typeof extractPoll === 'object' && extractPoll !== null && typeof extractPoll.unref === 'function') {
          extractPoll.unref()
        }
      }

      // ── teardown ──────────────────────────────────────────────────────────
      ctx.effect(function () {
        return function () {
          document.removeEventListener('dragover', onDragOverCapture, true)
          document.removeEventListener('drop', onDropCapture, true)
          document.removeEventListener('paste', onPasteCapture, true)
          if (extractObserver !== null) extractObserver.disconnect()
          if (extractPoll !== null) clearInterval(extractPoll)
          for (var controller of activeUploads) controller.abort()
          activeUploads.clear()
          dockItems = []
          dockListeners.clear()
        }
      }, 'file-attach: teardown')
    },
  }
}

    var plugin = buildFileAttachPlugin({ React: require("react"), Core: FileAttachCore });
    exports.name = plugin.name;
    exports.inject = plugin.inject;
    exports.apply = plugin.apply;
    return module.exports;
  }
});
