#!/usr/bin/env node
/**
 * Build the web client bundle for dsh-file-attach.
 *
 * The bundle must be exactly the module-table handoff shape the web shell
 * expects (see dsh-client-modules): a classic script that calls
 * `window.__ModuleLoader__.load({ id, factory })`, where `factory(require)`
 * returns the plugin's exports. `id` is the package name (the graph row id).
 *
 * The two plain scripts in src/ are inlined verbatim into the factory body;
 * `buildFileAttachPlugin(env)` produces { name, inject, apply }.
 *
 * Usage: node scripts/build-client.mjs   (writes lib/client.js)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
const core = readFileSync(path.join(root, 'src', 'client-core.js'), 'utf8')
const app = readFileSync(path.join(root, 'src', 'client-app.js'), 'utf8')

const banner = `/**
 * Generated by scripts/build-client.mjs from src/client-core.js + src/client-app.js.
 * Do not edit by hand; regenerate with \`npm run build:client\`.
 */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`
const tail = `
    var plugin = buildFileAttachPlugin({ React: require("react"), Core: FileAttachCore });
    exports.name = plugin.name;
    exports.inject = plugin.inject;
    exports.apply = plugin.apply;
    return module.exports;
  }
});
`

writeFileSync(path.join(root, 'lib', 'client.js'), banner + core + '\n' + app + tail)
console.log('wrote lib/client.js')
